// <auto-generated />
using BookLink.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookLink.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250121195316_AddCategoryTableToDbAndSeed")]
    partial class AddCategoryTableToDbAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookLink.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = -1,
                            CategoryName = "Literature"
                        },
                        new
                        {
                            CategoryId = -2,
                            CategoryName = "History"
                        },
                        new
                        {
                            CategoryId = -3,
                            CategoryName = "Economics"
                        },
                        new
                        {
                            CategoryId = -4,
                            CategoryName = "Medicine & Health"
                        },
                        new
                        {
                            CategoryId = -5,
                            CategoryName = "Religions & Beliefs"
                        },
                        new
                        {
                            CategoryId = -6,
                            CategoryName = "Self-Development"
                        },
                        new
                        {
                            CategoryId = -7,
                            CategoryName = "Science Fiction & Fantasy"
                        },
                        new
                        {
                            CategoryId = -8,
                            CategoryName = "Philosophy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
